# Use root/example as user/password credentials
version: '2'
#
services:
  db:
    image: mysql:5.5
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=barry_root
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=barry
        - MYSQL_DATABASE=dbtest
#    ports:
#       - "3306:3306"
    networks:
       - net-spring-db

  dbsetup:
    depends_on: 
      - db  
    image: cybernostics/liquibaseinit:0.0.1-SNAPSHOT
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/dbtest
      spring.datasource.username: dbuser
      spring.datasource.password: barry   
      maven.local.repo: /.m2/repository
      db.migrations: >
        [{"changeLogRoot":"gav:au.com.cybernostics.changesets:changeset1", 
        "changelogs":["db/changelog/db.changelog-master.yaml",
        "db/changelog2/db.changelog-master.yaml"
        ]}]
    networks:
      - net-spring-db
    volumes:
      - /home/jason/.m2:/.m2    

networks:
  net-spring-db:
      driver: bridge    
